version: '3.7'

services:
  db:
    restart: always
    image: mysql:latest 
    env_file:
      - .env
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379    
  app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile 
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
     - db
     - redis
